### ISSUE TITLE
Release v1.0.3 on the Chrome WebStore

### ISSUE THREAD

**Issue by jwhitcraft** [square/jirafy#12]
Currently on the Chrome WebStore has version 1.0.2 but in GitHub there is 1.0.3 that will open links in a new window, can this be update on the Chrome WebStore?

Thanks,

**Comment by aivus** [comment]
Version: 1.1 in chrome webstore. Issue could be closed.

> We should also tag releases for easy diffing.
It would be great.

**Comment by edenman** [comment]
Closing in favor of #18
